name: gitflow-oss-java-slim
description: "Common build conventions for OSS Gradle Java projects"
author: vacco
branding:
  icon: aperture
  color: white
inputs:
  orgConfig:
    description: "URL pointing to an Org Config JSON file to drive the build."
    required: true
runs:
  using: node20
  main: gs-action/dist/main.js
