name: gitflow-oss-java-slim
description: "Common build conventions for OSS Gradle Java projects"
author: vacco
branding:
  icon: aperture
  color: white
runs:
  using: docker
  image: docker://docker.io/library/gradle:8-jdk21
  args: [gradle, build]
inputs:
  orgConfig:
    description: "URL pointing to an Org Config JSON file to drive the build."
    required: true
