[book]
authors = ["Jesus Zazueta"]
language = "en"
multilingual = false
src = "."
title = "Gitflow Slim for Java OSS"

[preprocessor.variables.variables]
gsVersion = "0.9.9"

[build]
build-dir = "../docs"
