[book]
authors = ["Jesus Zazueta"]
language = "en"
multilingual = false
src = "."
title = "Gitflow Slim for Java OSS"

[preprocessor.variables.variables]
gsVersion = "1.8.3"

[build]
build-dir = "../docs"
